baseURL = "https://blog.lumingba.cn"

# [en, zh-cn, fr, ...] 设置默认的语言
defaultContentLanguage = "zh-cn"

# 网站语言, 仅在这里 CN 大写
languageCode = "zh-CN"

# 是否包括中日韩文字
hasCJKLanguage = true

# 网站标题
title = "芦明宝的博客 | 见自己、见天地、见众生"

# 更改使用 Hugo 构建网站时使用的默认主题
theme = "LoveIt"

# 是否使用 emoji 代码
enableEmoji = true

[outputs]
    home = ["HTML", "RSS", "JSON"]

[params]
    # LoveIt 主题版本
    version = "0.2.X"
    subtitle = "「见自己、见天地、见众生」"
    author = "芦明宝"
    keywords = "芦明宝,lumingbao,lumingbao.cn,java,spring,springboot,docker,mysql,芦明宝的博客"
    description = "见自己、见天地、见众生"
    busuanzi = false
    fancybox = true
    googleAd = ""  #ca-pub-xxxxxxxxxxxxxx
    localSearch = true # 启用本地搜索
    # 网站默认主题 ("light", "dark", "auto")
    defaultTheme = "auto"
    # date format
    # 日期格式
    dateFormat = "2006-01-02"

    # LoveIt 新增 | 0.2.0 搜索配置
    [params.search]
        enable = true
        # 搜索引擎的类型 ("lunr", "algolia")
        type = "algolia"
        # 文章内容最长索引长度
        contentLength = 4000
        # 搜索框的占位提示语
        placeholder = ""
        # LoveIt 新增 | 0.2.1 最大结果数目
        maxResultLength = 10
        # LoveIt 新增 | 0.2.3 结果内容片段长度
        snippetLength = 50
        # LoveIt 新增 | 0.2.1 搜索结果中高亮部分的 HTML 标签
        highlightTag = "em"
        # LoveIt 新增 | 0.2.4 是否在搜索索引中使用基于 baseURL 的绝对路径
        absoluteURL = false
        [params.search.algolia]
            index = "blog.lumingbao.cn"
            appID = "JQTRDUJFL3"
            searchKey = "0ac93a0f3c65a7ec95ab3858c4277679"

    # 页面头部导航栏配置
    [params.header]
        # 桌面端导航栏模式 ("fixed", "normal", "auto")
        desktopMode = "auto"
        # 移动端导航栏模式 ("fixed", "normal", "auto")
        mobileMode = "auto"
        # LoveIt 新增 | 0.2.0 页面头部导航栏标题配置
        [params.header.title]
            # LOGO 的 URL
            logo = ""
            # 标题名称
            name = "芦明宝的博客"
            # 你可以在名称 (允许 HTML 格式) 之前添加其他信息, 例如图标
            pre = ""
            # 你可以在名称 (允许 HTML 格式) 之后添加其他信息, 例如图标
            post = ""
            # LoveIt 新增 | 0.2.5 是否为标题显示打字机动画
            typeit = true

    # Footer config
    # 页面底部信息配置
    [params.footer]
        enable = true
        # Custom content (HTML format is supported)
        # 自定义内容 (支持 HTML 格式)
        custom = ''
        # whether to show Hugo and theme info
        # 是否显示 Hugo 和主题信息
        hugo = false
        # whether to show copyright info
        # 是否显示版权信息
        copyright = true
        # whether to show the author
        # 是否显示作者
        author = true
        # site creation time
        # 网站创立年份
        since = 2021
        # ICP info only in China (HTML format is supported)
        # ICP 备案信息，仅在中国使用 (支持 HTML 格式)
        icp = "陇ICP备2021002622号-1"
        # license info (HTML format is supported)
        # 许可协议信息 (支持 HTML 格式)
        license= 'lumingbao'
    [params.profile]
        enable=false

[menu]
    [[menu.main]]
        identifier = ""
        # 你可以在名称 (允许 HTML 格式) 之前添加其他信息, 例如图标
        pre = "<i class='fa fa-home'></i>"
        # 你可以在名称 (允许 HTML 格式) 之后添加其他信息, 例如图标
        post = ""
        name = "首页"
        url = "/"
        # 当你将鼠标悬停在此菜单链接上时, 将显示的标题
        title = ""
        weight = 1
    [[menu.main]]
        identifier = "posts"
        # 你可以在名称 (允许 HTML 格式) 之前添加其他信息, 例如图标
        pre = "<i class='fa fa-list'></i>"
        # 你可以在名称 (允许 HTML 格式) 之后添加其他信息, 例如图标
        post = ""
        name = "文章"
        url = "/posts/"
        # 当你将鼠标悬停在此菜单链接上时, 将显示的标题
        title = ""
        weight = 2
    [[menu.main]]
        identifier = "tags"
        pre = "<i class='fa fa-tags'></i>"
        post = ""
        name = "标签"
        url = "/tags/"
        title = ""
        weight = 3
    [[menu.main]]
        identifier = "categories"
        pre = "<i class='fa fa-adjust'></i>"
        post = ""
        name = "分类"
        url = "/categories/"
        title = ""
        weight = 4
    [[menu.main]]
       identifier = "friend"
       pre = "<i class='fa fa-link'></i>"
       post = ""
       name = "友链"
       url = "/friend/"
       title = ""
       weight = 5
    [[menu.main]]
       identifier = "about"
       pre = "<i class='fa fa-info-circle'></i>"
       post = ""
       name = "关于"
       url = "/about/"
       title = ""
       weight = 6
# Hugo 解析文档的配置
[markup]
    # 语法高亮设置 (https://gohugo.io/content-management/syntax-highlighting)
    [markup.highlight]
    # false 是必要的设置 (https://github.com/dillonzq/LoveIt/issues/158)
    noClasses = false
